on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]

name: Run tests
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - uses: mozilla-actions/sccache-action@v0.0.9

      - name: Patch azure linux deps
        run: sudo apt update

      - name: Install linux deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev libasound2-dev

      - name: cargo test
        run: cargo test ci_
